require('dotenv').config();
const express = require('express');
const cors = require('cors');
const pool = require('./db/pool');
const app = express();
app.use(cors());
app.use(express.json());
app.get('/api/health', (_req,res)=>res.json({status:'ok'}));
app.use('/api/users', require('./routes/users')(pool));
app.use('/api/rides', require('./routes/rides')(pool));
app.use('/api/requests', require('./routes/requests')(pool));
app.use('/api/trips', require('./routes/trips')(pool));
app.use('/api/ratings', require('./routes/ratings')(pool));
app.use((err,_req,res,_next)=>{console.error(err);res.status(500).json({error:'Unexpected server error.'});});
const port=process.env.PORT||4000; app.listen(port,()=>console.log(`WeShare API running on http://localhost:${port}`));
